export const GAME_DATA =
[
    [   {square: {row:0 ,col:3 , val:2 }},
        {square: {row:0 ,col:4 , val:6 }},
        {square: {row:0 ,col:6 , val:7 }},
        {square: {row:0 ,col:8 , val:1 }},
        {square: {row:1 ,col:0 , val:6 }},
        {square: {row:1 ,col:1 , val:8 }},
        {square: {row:1 ,col:4 , val:7 }},
        {square: {row:1 ,col:7 , val:9 }},
        {square: {row:2 ,col:0 , val:1 }},
        {square: {row:2 ,col:1 , val:9 }},
        {square: {row:2 ,col:5 , val:4 }},
        {square: {row:2 ,col:6 , val:5 }},
        {square: {row:3 ,col:0 , val:8 }},
        {square: {row:3 ,col:1 , val:2 }},
        {square: {row:3 ,col:3 , val:1 }},
        {square: {row:3 ,col:7 , val:4 }},
        {square: {row:4 ,col:2 , val:4 }},
        {square: {row:4 ,col:3 , val:6 }},
        {square: {row:4 ,col:5 , val:2 }},
        {square: {row:4 ,col:6 , val:9 }},
        {square: {row:5 ,col:1 , val:5 }},
        {square: {row:5 ,col:5 , val:3 }},
        {square: {row:5 ,col:7 , val:2 }},
        {square: {row:5 ,col:8 , val:8 }},
        {square: {row:6 ,col:2 , val:9 }},
        {square: {row:6 ,col:3 , val:3 }},
        {square: {row:6 ,col:7 , val:7 }},
        {square: {row:6 ,col:8 , val:4 }},
        {square: {row:7 ,col:1 , val:4 }},
        {square: {row:7 ,col:4 , val:5 }},
        {square: {row:7 ,col:7 , val:3 }},
        {square: {row:7 ,col:8 , val:6 }},
        {square: {row:8 ,col:0 , val:7 }},
        {square: {row:8 ,col:2 , val:3 }},
        {square: {row:8 ,col:4 , val:1 }},
        {square: {row:8 ,col:5 , val:8 }},],
    [
        {square: {row:0, col:1, val:2 }},
        {square: {row:0, col:3, val:6 }},
        {square: {row:0, col:5, val:8 }},
        {square: {row:1, col:0, val:5 }},
        {square: {row:1, col:1, val:8 }},
        {square: {row:1, col:5, val:9 }},
        {square: {row:1, col:6, val:7 }},
        {square: {row:2, col:4, val:4 }},
        {square: {row:3, col:0, val:3 }},
        {square: {row:3, col:1, val:7 }},
        {square: {row:3, col:6, val:5 }},
        {square: {row:4, col:0, val:6 }},
        {square: {row:4, col:8, val:4 }},
        {square: {row:5, col:2, val:8 }},
        {square: {row:5, col:7, val:1 }},
        {square: {row:5, col:8, val:3 }},
        {square: {row:6, col:4, val:2 }},
        {square: {row:7, col:2, val:9 }},
        {square: {row:7, col:3, val:8 }},
        {square: {row:7, col:7, val:3 }},
        {square: {row:7, col:8, val:6 }},
        {square: {row:8, col:3, val:3 }},
        {square: {row:8, col:5, val:6 }},
        {square: {row:8, col:7, val:9 }},
    ],
    [
        {square: {row:0, col:3, val:6 }},
        {square: {row:0, col:4, val:4 }},
        {square: {row:1, col:0, val:7 }},
        {square: {row:1, col:5, val:3 }},
        {square: {row:1, col:6, val:6 }},
        {square: {row:2, col:4, val:9 }},
        {square: {row:2, col:5, val:1 }},
        {square: {row:2, col:7, val:8 }},
        {square: {row:4, col:1, val:5 }},
        {square: {row:4, col:3, val:1 }},
        {square: {row:4, col:4, val:8 }},
        {square: {row:4, col:8, val:3 }},
        {square: {row:5, col:3, val:3 }},
        {square: {row:5, col:5, val:6 }},
        {square: {row:5, col:7, val:4 }},
        {square: {row:5, col:8, val:5 }},
        {square: {row:6, col:1, val:4 }},
        {square: {row:6, col:3, val:2 }},
        {square: {row:6, col:7, val:6 }},
        {square: {row:7, col:0, val:9 }},
        {square: {row:7, col:2, val:3 }},
        {square: {row:8, col:1, val:2 }},
        {square: {row:8, col:6, val:1 }},
    ]    
];